//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkPharmaciec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avail
    {
        public int ID { get; set; }
        public int IDDrug { get; set; }
        public string Quantity { get; set; }
        public string Price { get; set; }
        public string IDPharm { get; set; }
    
        public virtual Drugs Drugs { get; set; }
        public virtual Pharmacies Pharmacies { get; set; }
    }
}
