//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkPharmaciec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drugs
    {
        public int ID { get; set; }
        public string TitleDrug { get; set; }
        public string FormRelease { get; set; }
        public string Dosage { get; set; }
        public string Maker { get; set; }
        public string ShelfLife { get; set; }
    }
}
