//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkPharmaciec
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NetPharmaciesEntities5 : DbContext
    {
        public NetPharmaciesEntities5()
            : base("name=NetPharmaciesEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avail> Avail { get; set; }
        public virtual DbSet<Drugs> Drugs { get; set; }
        public virtual DbSet<Pharmacies> Pharmacies { get; set; }
    }
}
